services:
  - type: web
    name: nodejs
    runtime: docker
    repo: https://github.com/deahdennis/git-app-node.git
    envVars:
      - key: MONGO_USERNAME
        value: dennisdeah
      - key: MONGO_PASSWORD
        value: 12345678 
      - key: MONGO_HOSTNAME
        value: db 
      - key: MONGO_PORT
        value: 27017
      - key: MONGO_DB
        value: deliverydb
    disk:
      name: data
      mountPath: /data/node/app

  - type: web
    name: mongodb
    runtime: docker
    image: 
      url:  mongo:4.4
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: tecsup
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: 12345678
